sonic:
  agent:
    host: 10.58.15.155
    port: 7777
    key: 2f489c4c-a3f3-4721-bcfe-77f4a8a40fe9
  server:
    host: 10.179.2.21
    folder-port: 8094
    transport-port: 8095

modules:
  android:
    enable: true
    use-adbkit: true
  ios:
    enable: false
    wda-bundle-id: com.fosun.WebDriverAgentRunner.xctrunner
  appium:
    enable: true
  webview:
    enable: true
    chrome-driver-debug-port: 7778
    chrome-driver-path: C:\Program Files\Google\Chrome\Application\chromedriver.exe

logging:
  file:
    name: logs/sonic-agent.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"